# Generated by Django 5.0.6 on 2024-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0003_subscription_delete_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
